spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: hr-produtos
          uri: lb://hr-produtos
          predicates:
            - Path=/api/produtos/**
        - id: hr-nota-fiscal
          uri: lb://hr-nota-fiscal
          predicates:
            - Path=/nota-fiscal/**
        - id: hr-user
          uri: lb://hr-user
          predicates:
            - Path=/nota-fiscal/**
        - id: hr-user
          uri: lb://hr-oauth
          predicates:
            - Path=/hr-oauth/**
server:
  port: 8765
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka